### ISSUE TITLE
An error happens in gojira command

### ISSUE THREAD

**Issue by AlanChiou** [EC-Mobile/bitrise-step-gojira#5]
Full logs on Bitrise:
```
+------------------------------------------------------------------------------+

| (0) Go Jira                                                                  |
+------------------------------------------------------------------------------+
| id: https://github.com/Shebella/bitrise-step-gojira.git                      |
| version: develop                                                             |
| collection: git                                                              |
| toolkit: bash                                                                |
| time: 2021-12-20T10:46:18Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[10:46:18] Start installing (git) with apt-get          
INFO[10:46:18]  * [OK] Step dependency (git) installed, available. 
INFO[10:46:18] Start installing (wget) with apt-get         
INFO[10:46:18]  * [OK] Step dependency (wget) installed, available. 
+ echo 'This is the value specified for the input '\''example_step_input'\'': '
This is the value specified for the input 'example_step_input': 
+ envman add --key EXAMPLE_STEP_OUTPUT --value 'the value you want to share'
+ GOJIRA_VERSION=0.2.1
+ export GOJIRA_BASEURL=[REDACTED]
+ GOJIRA_BASEURL=[REDACTED]
+ export GOJIRA_USERNAME=[REDACTED]
+ GOJIRA_USERNAME=[REDACTED]
+ export 'GOJIRA_PASSWORD=[REDACTED]'
+ GOJIRA_PASSWORD='[REDACTED]'
+ curl -LO https://github.com/junkpiano/gojira/releases/download/0.2.1/gojira-linux-amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   661  100   661    0     0   3692      0 --:--:-- --:--:-- --:--:--  3692

  0 4795k    0 27542    0     0  58976      0  0:01:23 --:--:--  0:01:23 58976
100 4795k  100 4795k    0     0  8946k      0 --:--:-- --:--:-- --:--:-- 68.4M
+ unzip gojira-linux-amd64.zip
Archive:  gojira-linux-amd64.zip
   creating: gojira-linux-amd64/
  inflating: gojira-linux-amd64/gojira  
+ cd gojira-linux-amd64
+ ./gojira assignee --jql 'project=NSMAA AND status=Merged  AND key in (NSMAA-852,NSMAA-854,NSMAA-769,NSMAA-775,NSMAA-859,NSMAA-555,NSMAA-769)' --reporter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x722f63]
goroutine 1 [running]:
main.AssigneeCommand.func1(0xc0000ba840, 0x0, 0xc00010e040)
	/Users/yusuke.a.ohashi/src/github.com/junkpiano/gojira/assignee.go:31 +0x193
github.com/urfave/cli.HandleAction(0x76e480, 0x800570, 0xc0000ba840, 0xc0000ba840, 0x0)
	/Users/yusuke.a.ohashi/src/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:514 +0xbe
github.com/urfave/cli.Command.Run(0x7e8f74, 0x8, 0x0, 0x0, 0xc00008ccc0, 0x1, 0x1, 0x7eae8b, 0xf, 0x0, ...)
	/Users/yusuke.a.ohashi/src/go/pkg/mod/github.com/urfave/cli@v1.21.0/command.go:171 +0x4d2
github.com/urfave/cli.(*App).Run(0xc00010a000, 0xc0000aa000, 0x5, 0x5, 0x0, 0x0)
	/Users/yusuke.a.ohashi/src/go/pkg/mod/github.com/urfave/cli@v1.21.0/app.go:265 +0x733
main.main()
	/Users/yusuke.a.ohashi/src/github.com/junkpiano/gojira/app.go:20 +0x28a
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Go Jira (exit code: 2)                                        | 12.12 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/EC-Mobile/bitrise-step-gojira/issues       |
| Source: https://github.com/EC-Mobile/bitrise-step-gojira                     |
+---+---------------------------------------------------------------+----------+
```

**Comment by AlanChiou** [comment]
This doesn't happen for a long time, so I close it.
